### ISSUE TITLE
Replace Wikipedia links

### ISSUE THREAD

**Issue by phoerious** [SaraJo/SOPA-PIPA-Protest-Page#15]
Hi there,

great work. I will use a modified version of this blackout page on refining-linux.org.
There is one thing you should consider: the Wikipedia link to the article about PIPA is pretty much useless because Wikipedia will be blacked out as well. You should replace that link with another resource.

Cheers
Janek

**Comment by SaraJo** [comment]
Great call!!!!!!!

**Comment by phoerious** [comment]
Thanks. :-)

**Comment by SaraJo** [comment]
fixed!

**Comment by phoerious** [comment]
Maybe you could also remove the webfont inclusion for "Six Caps". This font isn't used and therefore you don't need to include it.
